name: Compile Backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Navigate to backend directory and compile using Maven
      - name: Build backend with Maven
        working-directory: app
        run: mvn clean compile

      # (Optional) Run tests
      # - name: Run tests
      #   working-directory: app
      #   run: mvn t
